[package]
name = "irb"
version = "0.1.0"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]

[dependencies]
irbacs-sys = { git = "https://github.com/gadomski/irbasc-sys", optional = true }
quick-error = "1.2"

[dev-dependencies]
approx = "0.1"
